[package]
name = "rust"
version = "0.1.0"
edition = "2021"

[dependencies]
prost = "0.9"
structopt = "0.3.25"
tokio = { version = "1.0", features = ["macros", "rt-multi-thread"] }
tonic = "0.6"
tracing = "0.1.29"
tracing-subscriber = "0.3.5"

[build-dependencies]
tonic-build = "0.6"
